apiVersion: v1
kind: Service
metadata:
  name: image-detector-service
spec:
  selector:
    app: image-detector-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  