name: Deploy to EC2

on:
  push:
    branches:
      - master


env:
  HOSTNAME: ${{ secrets.HOSTNAME }}
  USERNAME: ${{ secrets.USERNAME }}
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment values
        run: |
          echo "EC2_HOST: ${{ env.HOSTNAME }}"
          echo "EC2_USER: ${{ env.USERNAME }}"
          echo "DOCKER_IMAGE_NAME: ${{ env.DOCKER_IMAGE_NAME }}"

      - name: Print environment variables
        run: printenv

